### PR TITLE
Support sub menus

### PR DESCRIPTION
**Pull request by RichardHowells**
Add support for submenus (menus that are more than two levels deep)

### CODE REVIEW

**Comment by ChrisHammond** [comment]
Richard, it looks like you made CSS changes to the bootstrap files? If you need to override the bootstrap CSS, please do so by adding CSS in the Skin.CSS file.

Otherwise the changes will always be lost by updates to bootstrap (as I performed in the latest release)

**Comment by RichardHowells** [comment]
Reversed those changes and moved my css mod to skin.css.

We did have a conversation about this (https://github.com/ChrisHammond/HammerFlex/issues/20) whic left me thinking I should change both bootstrap.css and bootstrap.min.css.

**Comment by ChrisHammond** [comment]
Thanks Richard, I'll see if I can get this worked in here later this week!

Chris

**Comment by RichardHowells** [comment]
Hi Chris - when can we get this merged?

**Comment by RichardHowells** [comment]
Hi Chris - when can we get this merged?  It is not open source when your changes go through because you want them.  Anyone else's don't get merged.  You did *ask* for this pull request (https://github.com/ChrisHammond/HammerFlex/issues/20).  It does not encourage me to contribute when you leave it on the shelf.

**Comment by ChrisHammond** [comment]
Richard, I simply haven't had time, my DNN work is limited due to my full time job.

I promise I will get this in, but I don't have a timeline for it right now.

**Comment by RichardHowells** [comment]
Yay.  Thank you.

**Pull request merged**
